"""
Draft generation utilities for speculative decoding.

This module provides a DraftModel wrapper that uses a small model adapter to
generate candidate tokens for speculative decoding. It supports configurable
draft lengths, greedy or sampling-based generation (via GenerationConfig),
and lightweight quality heuristics for adaptive draft length.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass

from air.interfaces.adapter import ModelAdapter
from air.types import GenerationConfig, Token


@dataclass(frozen=True)
class DraftResult:
    """
    Result from draft generation.

    Attributes:
        tokens: Draft tokens generated by the draft model.
        model_id: Identifier of the draft model used.
        max_draft_tokens: Maximum draft length requested for this generation.
        mean_logprob: Mean log probability of generated draft tokens.
        stopped_early: Whether generation stopped early due to heuristics.
    """

    tokens: list[Token]
    model_id: str
    max_draft_tokens: int
    mean_logprob: float
    stopped_early: bool


class DraftModel:
    """
    Draft generation wrapper for speculative decoding.

    This class orchestrates draft token generation using a ModelAdapter,
    enforcing a maximum draft window and providing lightweight heuristics
    for adaptive draft length based on recent log probabilities.
    """

    def __init__(
        self,
        adapter: ModelAdapter,
        default_draft_tokens: int = 8,
        min_draft_tokens: int = 1,
        max_draft_tokens: int = 32,
        logprob_stop_threshold: float = -5.0,
        logprob_window: int = 3,
        adaptive_draft: bool = True,
    ) -> None:
        """
        Initialize the draft model wrapper.

        Args:
            adapter: ModelAdapter used for draft generation.
            default_draft_tokens: Default number of draft tokens to generate.
            min_draft_tokens: Minimum tokens to generate before applying heuristics.
            max_draft_tokens: Maximum allowed draft tokens (hard cap).
            logprob_stop_threshold: If rolling mean logprob drops below this,
                draft generation stops early.
            logprob_window: Window size for rolling mean logprob calculation.
            adaptive_draft: Whether to enable adaptive stopping heuristics.

        Raises:
            ValueError: If any draft length or window settings are invalid.
        """
        if default_draft_tokens <= 0:
            raise ValueError("default_draft_tokens must be positive")
        if min_draft_tokens <= 0:
            raise ValueError("min_draft_tokens must be positive")
        if max_draft_tokens <= 0:
            raise ValueError("max_draft_tokens must be positive")
        if min_draft_tokens > max_draft_tokens:
            raise ValueError("min_draft_tokens cannot exceed max_draft_tokens")
        if logprob_window <= 0:
            raise ValueError("logprob_window must be positive")

        self._adapter = adapter
        self._default_draft_tokens = default_draft_tokens
        self._min_draft_tokens = min_draft_tokens
        self._max_draft_tokens = max_draft_tokens
        self._logprob_stop_threshold = logprob_stop_threshold
        self._logprob_window = logprob_window
        self._adaptive_draft = adaptive_draft

    @property
    def adapter(self) -> ModelAdapter:
        """Return the underlying model adapter."""
        return self._adapter

    @property
    def default_draft_tokens(self) -> int:
        """Return the default draft length."""
        return self._default_draft_tokens

    @property
    def max_draft_tokens(self) -> int:
        """Return the hard cap for draft length."""
        return self._max_draft_tokens

    def generate_draft(
        self,
        prompt: str,
        config: GenerationConfig,
        max_draft_tokens: int | None = None,
    ) -> DraftResult:
        """
        Generate a draft sequence from the adapter.

        Args:
            prompt: Input prompt text.
            config: GenerationConfig used for sampling parameters.
            max_draft_tokens: Optional override for draft length.

        Returns:
            DraftResult containing the generated draft tokens and metadata.

        Raises:
            RuntimeError: If the model adapter is not loaded.
            ValueError: If prompt is empty or draft length invalid.
        """
        if not self._adapter.is_loaded:
            raise RuntimeError("Draft model adapter is not loaded")
        if not prompt:
            raise ValueError("prompt must be non-empty")

        draft_limit = self._resolve_draft_limit(max_draft_tokens)

        effective_max_tokens = self._resolve_generation_limit(config, draft_limit)
        draft_config = self._build_draft_config(config, effective_max_tokens)

        tokens = []
        logprob_history: deque[float] = deque(maxlen=self._logprob_window)
        stopped_early = False

        for token in self._adapter.generate(prompt, draft_config):
            tokens.append(token)
            logprob_history.append(token.logprob)

            if len(tokens) >= effective_max_tokens:
                break

            if (
                self._adaptive_draft
                and len(tokens) >= self._min_draft_tokens
                and self._should_stop_early(logprob_history)
            ):
                stopped_early = True
                break

        mean_logprob = self._mean_logprob(tokens)
        return DraftResult(
            tokens=tokens,
            model_id=self._adapter.model_id,
            max_draft_tokens=effective_max_tokens,
            mean_logprob=mean_logprob,
            stopped_early=stopped_early,
        )

    def _resolve_draft_limit(self, max_draft_tokens: int | None) -> int:
        """Resolve the requested draft limit with validation and clamping."""
        draft_limit = (
            max_draft_tokens if max_draft_tokens is not None else self._default_draft_tokens
        )
        if draft_limit <= 0:
            raise ValueError("max_draft_tokens must be positive")
        return min(max(draft_limit, self._min_draft_tokens), self._max_draft_tokens)

    @staticmethod
    def _resolve_generation_limit(config: GenerationConfig, draft_limit: int) -> int:
        """Apply the draft limit to the generation config's max_tokens."""
        if config.max_tokens == -1:
            return draft_limit
        return max(1, min(config.max_tokens, draft_limit))

    @staticmethod
    def _build_draft_config(config: GenerationConfig, max_tokens: int) -> GenerationConfig:
        """Clone the config with an overridden max_tokens for draft generation."""
        config_data = config.to_dict()
        config_data["max_tokens"] = max_tokens
        return GenerationConfig.from_dict(config_data)

    def _should_stop_early(self, logprob_history: deque[float]) -> bool:
        """Return True when rolling mean logprob drops below the threshold."""
        mean_logprob = sum(logprob_history) / len(logprob_history)
        return mean_logprob < self._logprob_stop_threshold

    @staticmethod
    def _mean_logprob(tokens: list[Token]) -> float:
        """Compute the mean log probability of draft tokens."""
        if not tokens:
            return 0.0
        return sum(token.logprob for token in tokens) / len(tokens)
