"""
Inference state management for the Adaptive Inference Runtime.

This module provides the InferenceState class which tracks the complete state
of an inference session, including:
- Current model being used
- KV cache reference
- Generation parameters
- Token history and statistics

The state can be serialized/deserialized for persistence and supports
seamless model transitions during generation.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import (
    TYPE_CHECKING,
    Any,
    Dict,
    List,
    Optional,
    Sequence,
)

from air.types import (
    CompressionConfig,
    GenerationConfig,
    KVCache,
    Token,
)

if TYPE_CHECKING:
    pass


class ModelTier(str, Enum):
    """
    Enumeration of model tiers in the routing hierarchy.

    The routing system uses these tiers to track which level of model
    complexity is currently being used for generation.
    """

    SMALL = "small"
    """Small/fast model (e.g., 7B, 13B parameters)"""

    LARGE = "large"
    """Large/powerful model (e.g., 70B parameters)"""

    REMOTE = "remote"
    """Remote API model (e.g., OpenAI, Anthropic)"""


@dataclass
class TokenStats:
    """
    Statistics about generated tokens.

    Tracks metrics useful for monitoring generation quality and
    making routing decisions.
    """

    total_tokens: int = 0
    """Total number of tokens generated"""

    tokens_by_small_model: int = 0
    """Tokens generated by small model"""

    tokens_by_large_model: int = 0
    """Tokens generated by large model"""

    model_transitions: int = 0
    """Number of times the model was switched"""

    avg_logprob: float = 0.0
    """Running average of log probabilities"""

    min_logprob: float = float("inf")
    """Minimum log probability seen"""

    speculation_attempts: int = 0
    """Number of speculative decoding attempts"""

    speculation_acceptances: int = 0
    """Number of fully accepted speculation drafts"""

    def update(self, token: Token, model_tier: ModelTier) -> None:
        """
        Update statistics with a new token.

        Args:
            token: The newly generated token.
            model_tier: The tier of model that generated the token.
        """
        self.total_tokens += 1

        if model_tier == ModelTier.SMALL:
            self.tokens_by_small_model += 1
        elif model_tier == ModelTier.LARGE:
            self.tokens_by_large_model += 1

        # Update running average log probability
        if self.total_tokens == 1:
            self.avg_logprob = token.logprob
        else:
            self.avg_logprob = (
                self.avg_logprob * (self.total_tokens - 1) + token.logprob
            ) / self.total_tokens

        self.min_logprob = min(self.min_logprob, token.logprob)

    @property
    def small_model_ratio(self) -> float:
        """Ratio of tokens generated by small model."""
        if self.total_tokens == 0:
            return 0.0
        return self.tokens_by_small_model / self.total_tokens

    @property
    def speculation_acceptance_rate(self) -> float:
        """Rate of successful speculation attempts."""
        if self.speculation_attempts == 0:
            return 0.0
        return self.speculation_acceptances / self.speculation_attempts

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "total_tokens": self.total_tokens,
            "tokens_by_small_model": self.tokens_by_small_model,
            "tokens_by_large_model": self.tokens_by_large_model,
            "model_transitions": self.model_transitions,
            "avg_logprob": self.avg_logprob,
            "min_logprob": self.min_logprob if self.min_logprob != float("inf") else None,
            "speculation_attempts": self.speculation_attempts,
            "speculation_acceptances": self.speculation_acceptances,
            "small_model_ratio": self.small_model_ratio,
            "speculation_acceptance_rate": self.speculation_acceptance_rate,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TokenStats":
        """Create from dictionary representation."""
        stats = cls()
        stats.total_tokens = data.get("total_tokens", 0)
        stats.tokens_by_small_model = data.get("tokens_by_small_model", 0)
        stats.tokens_by_large_model = data.get("tokens_by_large_model", 0)
        stats.model_transitions = data.get("model_transitions", 0)
        stats.avg_logprob = data.get("avg_logprob", 0.0)
        min_lp = data.get("min_logprob")
        stats.min_logprob = min_lp if min_lp is not None else float("inf")
        stats.speculation_attempts = data.get("speculation_attempts", 0)
        stats.speculation_acceptances = data.get("speculation_acceptances", 0)
        return stats


class InferenceState:
    """
    Complete state of an inference session.

    InferenceState tracks everything needed to manage and monitor an
    inference session, including the current model, KV cache, generation
    configuration, and token history. It supports serialization for
    persistence and seamless model transitions.

    The state is the central coordination point for:
    - Routing decisions (which model to use)
    - Speculative decoding (draft/verify coordination)
    - KV cache compression (memory management)
    - Session metrics and monitoring

    Attributes:
        model_id: Identifier of the current model.
        model_tier: Tier (small/large/remote) of the current model.
        generation_config: Current generation parameters.
        compression_config: Current compression settings.
        token_history: List of generated tokens.
        stats: Token generation statistics.
        created_at: Timestamp when state was created.
        last_updated_at: Timestamp of last update.

    Example:
        >>> from air import InferenceState, GenerationConfig
        >>> config = GenerationConfig(max_tokens=256, temperature=0.7)
        >>> state = InferenceState(
        ...     model_id="llama-7b",
        ...     generation_config=config
        ... )
        >>> state.add_token(Token(id=123, text="Hello", logprob=-0.5))
        >>> state.token_count
        1
    """

    def __init__(
        self,
        model_id: str,
        generation_config: Optional[GenerationConfig] = None,
        compression_config: Optional[CompressionConfig] = None,
        model_tier: ModelTier = ModelTier.SMALL,
        kv_cache: Optional[KVCache] = None,
        max_history_length: int = 10000,
    ) -> None:
        """
        Initialize a new inference state.

        Args:
            model_id: Identifier of the initial model.
            generation_config: Generation parameters (uses defaults if None).
            compression_config: Compression settings (uses defaults if None).
            model_tier: Initial model tier.
            kv_cache: Optional initial KV cache reference.
            max_history_length: Maximum tokens to keep in history.
        """
        self._model_id: str = model_id
        self._model_tier: ModelTier = model_tier
        self._generation_config: GenerationConfig = (
            generation_config or GenerationConfig()
        )
        self._compression_config: CompressionConfig = (
            compression_config or CompressionConfig()
        )
        self._kv_cache: Optional[KVCache] = kv_cache
        self._token_history: List[Token] = []
        self._max_history_length: int = max_history_length
        self._stats: TokenStats = TokenStats()
        self._created_at: float = time.time()
        self._last_updated_at: float = self._created_at
        self._metadata: Dict[str, Any] = {}
        self._logprob_window: List[float] = []
        self._logprob_window_size: int = 20

    # =========================================================================
    # Properties
    # =========================================================================

    @property
    def model_id(self) -> str:
        """Get the current model identifier."""
        return self._model_id

    @property
    def model_tier(self) -> ModelTier:
        """Get the current model tier."""
        return self._model_tier

    @property
    def generation_config(self) -> GenerationConfig:
        """Get the current generation configuration."""
        return self._generation_config

    @property
    def compression_config(self) -> CompressionConfig:
        """Get the current compression configuration."""
        return self._compression_config

    @property
    def kv_cache(self) -> Optional[KVCache]:
        """Get the current KV cache reference."""
        return self._kv_cache

    @property
    def token_history(self) -> Sequence[Token]:
        """Get the token history (read-only view)."""
        return self._token_history

    @property
    def token_count(self) -> int:
        """Get the number of tokens in history."""
        return len(self._token_history)

    @property
    def stats(self) -> TokenStats:
        """Get the token statistics."""
        return self._stats

    @property
    def created_at(self) -> float:
        """Get the creation timestamp."""
        return self._created_at

    @property
    def last_updated_at(self) -> float:
        """Get the last update timestamp."""
        return self._last_updated_at

    @property
    def metadata(self) -> Dict[str, Any]:
        """Get custom metadata dictionary."""
        return self._metadata

    @property
    def recent_logprobs(self) -> List[float]:
        """Get recent log probabilities for slope calculation."""
        return self._logprob_window.copy()

    @property
    def is_using_small_model(self) -> bool:
        """Check if currently using small model."""
        return self._model_tier == ModelTier.SMALL

    @property
    def is_using_large_model(self) -> bool:
        """Check if currently using large model."""
        return self._model_tier == ModelTier.LARGE

    @property
    def last_token(self) -> Optional[Token]:
        """Get the most recently generated token."""
        if self._token_history:
            return self._token_history[-1]
        return None

    @property
    def last_n_tokens(self) -> List[Token]:
        """Get the last N tokens (N = logprob_window_size)."""
        return self._token_history[-self._logprob_window_size:]

    # =========================================================================
    # State Update Methods
    # =========================================================================

    def update(
        self,
        *,
        model_id: Optional[str] = None,
        model_tier: Optional[ModelTier] = None,
        generation_config: Optional[GenerationConfig] = None,
        compression_config: Optional[CompressionConfig] = None,
        kv_cache: Optional[KVCache] = None,
    ) -> None:
        """
        Update state with new values.

        Only provided parameters are updated; others retain their current values.

        Args:
            model_id: New model identifier.
            model_tier: New model tier.
            generation_config: New generation configuration.
            compression_config: New compression configuration.
            kv_cache: New KV cache reference.
        """
        if model_id is not None:
            self._model_id = model_id
        if model_tier is not None:
            self._model_tier = model_tier
        if generation_config is not None:
            self._generation_config = generation_config
        if compression_config is not None:
            self._compression_config = compression_config
        if kv_cache is not None:
            self._kv_cache = kv_cache

        self._last_updated_at = time.time()

    def add_token(self, token: Token) -> None:
        """
        Add a generated token to history.

        Args:
            token: The token to add.
        """
        self._token_history.append(token)

        # Maintain history size limit
        if len(self._token_history) > self._max_history_length:
            self._token_history = self._token_history[-self._max_history_length:]

        # Update logprob window
        self._logprob_window.append(token.logprob)
        if len(self._logprob_window) > self._logprob_window_size:
            self._logprob_window.pop(0)

        # Update statistics
        self._stats.update(token, self._model_tier)
        self._last_updated_at = time.time()

    def add_tokens(self, tokens: Sequence[Token]) -> None:
        """
        Add multiple tokens to history.

        Args:
            tokens: The tokens to add.
        """
        for token in tokens:
            self.add_token(token)

    def transition_to_model(
        self,
        model_id: str,
        model_tier: ModelTier,
        kv_cache: Optional[KVCache] = None,
        reason: str = "",
    ) -> None:
        """
        Transition to a different model.

        This method handles the state updates needed when switching models,
        including updating statistics and optionally transferring the KV cache.

        Args:
            model_id: The new model identifier.
            model_tier: The new model tier.
            kv_cache: Optional KV cache for the new model.
            reason: Human-readable reason for the transition.
        """
        old_model_id = self._model_id
        old_tier = self._model_tier

        self._model_id = model_id
        self._model_tier = model_tier
        if kv_cache is not None:
            self._kv_cache = kv_cache

        # Track transition in stats
        self._stats.model_transitions += 1

        # Record transition in metadata
        if "transitions" not in self._metadata:
            self._metadata["transitions"] = []
        self._metadata["transitions"].append({
            "from_model": old_model_id,
            "from_tier": old_tier.value,
            "to_model": model_id,
            "to_tier": model_tier.value,
            "at_token": self.token_count,
            "reason": reason,
            "timestamp": time.time(),
        })

        self._last_updated_at = time.time()

    def set_kv_cache(self, kv_cache: Optional[KVCache]) -> None:
        """
        Set the KV cache reference.

        Args:
            kv_cache: The new KV cache, or None to clear.
        """
        self._kv_cache = kv_cache
        self._last_updated_at = time.time()

    def clear_kv_cache(self) -> None:
        """Clear the KV cache reference."""
        if self._kv_cache is not None:
            self._kv_cache.clear()
        self._kv_cache = None
        self._last_updated_at = time.time()

    def set_metadata(self, key: str, value: Any) -> None:
        """
        Set a metadata value.

        Args:
            key: The metadata key.
            value: The value to store.
        """
        self._metadata[key] = value

    def record_speculation(self, accepted: bool) -> None:
        """
        Record a speculation attempt.

        Args:
            accepted: Whether the speculation was fully accepted.
        """
        self._stats.speculation_attempts += 1
        if accepted:
            self._stats.speculation_acceptances += 1

    # =========================================================================
    # Serialization Methods
    # =========================================================================

    def serialize(self) -> Dict[str, Any]:
        """
        Serialize state to a dictionary.

        Note: The KV cache is not serialized as it contains large tensors.
        Use serialize_full() if you need to persist the cache separately.

        Returns:
            Dictionary representation of the state.
        """
        return {
            "version": "1.0",
            "model_id": self._model_id,
            "model_tier": self._model_tier.value,
            "generation_config": self._generation_config.to_dict(),
            "compression_config": self._compression_config.to_dict(),
            "token_history": [
                {"id": t.id, "text": t.text, "logprob": t.logprob}
                for t in self._token_history
            ],
            "stats": self._stats.to_dict(),
            "created_at": self._created_at,
            "last_updated_at": self._last_updated_at,
            "metadata": self._metadata,
            "logprob_window": self._logprob_window,
        }

    @classmethod
    def deserialize(cls, data: Dict[str, Any]) -> "InferenceState":
        """
        Deserialize state from a dictionary.

        Args:
            data: Dictionary representation of the state.

        Returns:
            A new InferenceState instance.

        Raises:
            ValueError: If the data format is invalid.
        """
        version = data.get("version", "1.0")
        if version != "1.0":
            raise ValueError(f"Unsupported state version: {version}")

        state = cls(
            model_id=data["model_id"],
            model_tier=ModelTier(data["model_tier"]),
            generation_config=GenerationConfig.from_dict(data["generation_config"]),
            compression_config=CompressionConfig.from_dict(data["compression_config"]),
        )

        # Restore token history
        for t in data.get("token_history", []):
            token = Token(id=t["id"], text=t["text"], logprob=t["logprob"])
            state._token_history.append(token)

        # Restore statistics
        state._stats = TokenStats.from_dict(data.get("stats", {}))

        # Restore timestamps
        state._created_at = data.get("created_at", time.time())
        state._last_updated_at = data.get("last_updated_at", time.time())

        # Restore metadata
        state._metadata = data.get("metadata", {})

        # Restore logprob window
        state._logprob_window = data.get("logprob_window", [])

        return state

    def to_json(self) -> str:
        """
        Serialize state to JSON string.

        Returns:
            JSON representation of the state.
        """
        return json.dumps(self.serialize(), indent=2)

    @classmethod
    def from_json(cls, json_str: str) -> "InferenceState":
        """
        Deserialize state from JSON string.

        Args:
            json_str: JSON representation of the state.

        Returns:
            A new InferenceState instance.
        """
        return cls.deserialize(json.loads(json_str))

    # =========================================================================
    # Utility Methods
    # =========================================================================

    def get_text(self) -> str:
        """
        Get the full generated text from token history.

        Returns:
            Concatenated text from all tokens.
        """
        return "".join(t.text for t in self._token_history)

    def get_token_ids(self) -> List[int]:
        """
        Get list of token IDs from history.

        Returns:
            List of token IDs.
        """
        return [t.id for t in self._token_history]

    def clone(self) -> "InferenceState":
        """
        Create a deep copy of the state.

        Note: The KV cache is not cloned; use kv_cache.clone() separately
        if a deep copy of the cache is needed.

        Returns:
            A new InferenceState with copied data.
        """
        return self.deserialize(self.serialize())

    def reset(self) -> None:
        """
        Reset the state while keeping configuration.

        Clears token history, statistics, and KV cache while maintaining
        the current model and configuration settings.
        """
        self._token_history.clear()
        self._stats = TokenStats()
        self._logprob_window.clear()
        if self._kv_cache is not None:
            self._kv_cache.clear()
        self._metadata = {}
        self._last_updated_at = time.time()

    def __repr__(self) -> str:
        """Get string representation of state."""
        return (
            f"InferenceState("
            f"model_id='{self._model_id}', "
            f"tier={self._model_tier.value}, "
            f"tokens={self.token_count}, "
            f"transitions={self._stats.model_transitions})"
        )
